/**
 * Skill compressor — generate a condensed skill index for heavy profiles.
 */

import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = process.env.CUE_REPO_ROOT ?? process.env.SOUL_REPO_ROOT ?? resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SKILLS_ROOT = join(REPO_ROOT, "resources", "skills", "skills");

interface SkillSummary {
  id: string;
  description: string;
  triggers: string[];
  category: string;
}

function extractTriggers(content: string): string[] {
  const triggers: string[] = [];
  // Extract quoted phrases that look like trigger patterns
  const quotes = content.match(/"([^"]{5,60})"/g);
  if (quotes) triggers.push(...quotes.slice(0, 3).map(q => q.replace(/"/g, "")));
  // Extract slash commands
  const slashes = content.match(/\/[a-z][-a-z]+/g);
  if (slashes) triggers.push(...slashes.slice(0, 2));
  return triggers;
}

function summarizeSkill(id: string): SkillSummary | null {
  const path = join(SKILLS_ROOT, id, "SKILL.md");
  if (!existsSync(path)) return null;

  const content = readFileSync(path, "utf8");
  const category = id.split("/")[0] ?? "unknown";

  let description = "";
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (fmMatch) {
    const descMatch = fmMatch[1]!.match(/^description:\s*["']?(.+?)["']?\s*$/m);
    if (descMatch) description = descMatch[1]!;
  }
  if (!description) {
    const firstLine = content.split("\n").find(l => l.trim() && !l.startsWith("#") && !l.startsWith("---"));
    description = firstLine?.trim().slice(0, 100) ?? id;
  }

  return { id, description, triggers: extractTriggers(content), category };
}

export function generateSkillIndex(skillIds: string[], threshold = 10): string | null {
  if (skillIds.length <= threshold) return null;

  const summaries = skillIds.map(summarizeSkill).filter(Boolean) as SkillSummary[];

  let md = `# Skill Index (${summaries.length} skills loaded)\n\n`;
  md += `> This profile has many skills. Use this index to find the right one.\n`;
  md += `> For full details, read \`./skills/<category>/<name>/SKILL.md\`\n\n`;
  md += `| Skill | Trigger / Description | Category |\n`;
  md += `|---|---|---|\n`;

  for (const s of summaries) {
    const trigger = s.triggers.length ? s.triggers.join(", ") : s.description.slice(0, 60);
    md += `| ${s.id} | ${trigger} | ${s.category} |\n`;
  }

  md += `\n---\n*Index auto-generated by cue. ${summaries.length} skills compressed into ~${Math.ceil(md.length / 4)} tokens.*\n`;
  return md;
}
