/**
 * `cue export --docker` — generate a Dockerfile for a profile.
 *
 * Produces a Dockerfile that installs cue-ai, copies the profile,
 * installs CLI dependencies, and pre-materializes the runtime.
 */

import { writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { loadProfile } from "../lib/profile-loader";
import { resolveProfileForCwd } from "../lib/cwd-resolver";
import { homedir } from "node:os";

const REPO_ROOT = process.env.CUE_REPO_ROOT ?? process.env.SOUL_REPO_ROOT ?? resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

export async function run(args: string[]): Promise<number> {
  if (args.includes("-h") || args.includes("--help")) {
    process.stdout.write(`cue export --docker — generate a Dockerfile for a profile

Usage:
  cue export --docker [--profile <name>] [--output <path>] [--base <image>]

Options:
  --profile <name>  Profile to containerize (default: active)
  --output <path>   Output path (default: Dockerfile.cue)
  --base <image>    Base image (default: oven/bun:1-slim)
`);
    return 0;
  }

  const profileIdx = args.indexOf("--profile");
  let profileName = profileIdx >= 0 ? args[profileIdx + 1] : undefined;
  const outputIdx = args.indexOf("--output");
  const outputPath = outputIdx >= 0 ? args[outputIdx + 1] ?? "Dockerfile.cue" : "Dockerfile.cue";
  const baseIdx = args.indexOf("--base");
  const baseImage = baseIdx >= 0 ? args[baseIdx + 1] ?? "oven/bun:1-slim" : "oven/bun:1-slim";

  if (!profileName) {
    try {
      const result = await resolveProfileForCwd({ cwd: process.cwd(), homeDir: homedir(), configDir: join(homedir(), ".config", "cue") });
      if (result.source !== "none") profileName = result.profile;
    } catch {}
  }

  if (!profileName) {
    process.stderr.write("No active profile. Specify with --profile <name>\n");
    return 1;
  }

  const profile = await loadProfile(profileName);

  // Collect CLI deps from skills
  const cliDeps = extractCliDeps(profile);

  const dockerfile = generateDockerfile(profileName, baseImage, cliDeps);
  const dockerignore = generateDockerignore();

  writeFileSync(outputPath, dockerfile);
  writeFileSync(".dockerignore.cue", dockerignore);

  process.stdout.write(`✅ Generated ${outputPath} for profile "${profileName}"\n`);
  process.stdout.write(`   Also wrote .dockerignore.cue\n`);
  process.stdout.write(`   Build with: docker build -f ${outputPath} -t cue-${profileName} .\n`);
  return 0;
}

function extractCliDeps(profile: { skills: { local: { id: string }[] } }): string[] {
  const SKILLS_ROOT = join(REPO_ROOT, "resources", "skills", "skills");
  const { readFileSync } = require("node:fs");
  const clis = new Set<string>();

  for (const s of profile.skills.local) {
    const skillPath = join(SKILLS_ROOT, s.id, "SKILL.md");
    try {
      const content = readFileSync(skillPath, "utf8") as string;
      // Extract from ## Prerequisites
      const prereqMatch = content.match(/##\s*Prerequisites\s*\n([\s\S]*?)(?=\n##|\n$)/i);
      if (prereqMatch) {
        const installs = prereqMatch[1]!.match(/`([a-z][a-z0-9_-]+)`/g);
        if (installs) installs.forEach((m: string) => clis.add(m.replace(/`/g, "")));
      }
    } catch {}
  }
  return [...clis];
}

function generateDockerfile(profileName: string, baseImage: string, cliDeps: string[]): string {
  const aptDeps = cliDeps.filter(d => !["node", "bun", "npm", "npx"].includes(d));
  const aptLine = aptDeps.length ? `RUN apt-get update && apt-get install -y ${aptDeps.join(" ")} && rm -rf /var/lib/apt/lists/*` : "";

  return `# Generated by: cue export --docker --profile ${profileName}
# Build: docker build -f Dockerfile.cue -t cue-${profileName} .

FROM ${baseImage}

# Install system dependencies
RUN apt-get update && apt-get install -y curl git && rm -rf /var/lib/apt/lists/*

# Install cue-ai
RUN npm install -g cue-ai

${aptLine ? aptLine + "\n" : ""}# Copy profile
COPY profiles/${profileName}/ /app/profiles/${profileName}/
COPY resources/ /app/resources/

WORKDIR /app

# Pin profile
RUN echo "${profileName}" > .cue-profile

# Pre-materialize runtime
RUN cue use ${profileName} || true

ENV CLAUDE_CONFIG_DIR=/root/.config/cue/runtime/${profileName}/claude

ENTRYPOINT ["claude"]
`;
}

function generateDockerignore(): string {
  return `node_modules
.git
*.log
.env
.env.*
.DS_Store
tmp/
`;
}
